CREATE TABLE Students(
 ID INT NOT NULL UNIQUE,
 LastName VARCHAR(55) NOT NULL,
 FirstName VARCHAR(55) NOT NULL,
 Age INT
 );
 
 SHOW TABLES;
 
 INSERT INTO STUDENTS(ID,LASTNAME,FIRSTNAME,AGE) VALUES
 (1,'INKY','MAN',10),
 (2,'PINKY','MAN',20),
 (3,'CHINKY','MAN',30);
 
 SELECT* FROM STUDENTS;
 
 --  DIFFERENCE BETWEEN DROP, TRUNCATE, DELETE 
 TRUNCATE students;-- REMOVES ALL THE VALUS IN THE TABLE 
 DROP TABLE STUDENTS; -- DELETES  WHOLE TABLE (INCLUDING STRUCTURE )
 DELETE  FROM STUDENTS ;   -- EITHER DELECTE ALL VALUES OR IF THERE IS A CONDITION EXISTS DELETES SPECIC RECORDS 
 
 -----------------------------------------------------------------------------
 
 DELETE FROM STUDENTS 
 WHERE AGE >21;
 
 SELECT * FROM STUDENTS ; -- REMOVES ALL THE VALUS IN THE TABLE 